### ISSUE TITLE
Anteproyecto Beta

### ISSUE THREAD

**Issue by axelitz** [fiuba-labo-de-micro-miercoles/2019-2c-proyecto-Cofimetro#3]
Se subió una primera versión del anteproyecto del Cofímetro

**Comment by rarias** [comment]
Ver correcciones en 
https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-proyecto-Cofimetro/tree/master/doc/anteproyecto
Pasen a la versión 2 cuando hagan los cambios indicados.
